spring:
  profiles:
    group:
      "local" : "local, jwt, oauth"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/well_com
    username: root
    password: 1234

  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: mywellcombucket
    credentials:
      access-key: AKIASOJHOEEQEDOFWRHD
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false