spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, s3, mail"
    active : local
---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/well_com
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: false
        show_sql: false
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update