jwt:
  secretKey: ${JWT_SECRET_KEY}

  access:
    expiration: ${JWT_ACCESS_EXPIRE} # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: ${JWT_REFRESH_EXPIRE} #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: AuthorizationRefresh